# Configurable Settings

DEFAULT_COLORS = ['Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple', 'Cyan', 'Pink', 'Brown', 'Black']
DEFAULT_CODE_LENGTH = 4
DEFAULT_SLOT_COUNT = 4
DEFAULT_MAX_SLOTS = 6
DEFAULT_MIN_SLOTS = 2
DEFAULT_MAX_COLORS = 10
DEFAULT_MIN_COLORS = 2
DEFAULT_COLORS_COUNT = 6
DEFAULT_MAX_GUESSES = 10
